create table player  (
 player_id int NOT NULL GENERATED ALWAYS AS IDENTITY,
 season_id int NOT NULL,
 user_id int NOT NULL,
 team_id int NOT NULL,
 PRIMARY KEY (player_id),
CONSTRAINT P_S_FK FOREIGN KEY (season_id) REFERENCES season(season_id) ON DELETE CASCADE ON UPDATE RESTRICT ,
CONSTRAINT P_U_FK FOREIGN KEY (user_id)   REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE RESTRICT ,
CONSTRAINT P_T_FK FOREIGN KEY (team_id)   REFERENCES team(team_id) ON DELETE CASCADE ON UPDATE RESTRICT
)
